const menu = document.querySelector('.menu-toggle');
const nav = document.querySelector('#navigation');
menu.addEventListener('click', () => { const open = menu.getAttribute('aria-expanded') !== 'true'; menu.setAttribute('aria-expanded', String(open)); nav.classList.toggle('open', open); });
nav.querySelectorAll('a').forEach(a => a.addEventListener('click', () => { menu.setAttribute('aria-expanded', 'false'); nav.classList.remove('open'); }));
const gallery = document.querySelector('#gallery-dialog');
document.querySelectorAll('.project').forEach(button => button.addEventListener('click', () => { gallery.querySelector('img').src = button.dataset.image; gallery.querySelector('img').alt = button.querySelector('img').alt; gallery.querySelector('p').textContent = button.dataset.title; gallery.showModal(); }));
document.querySelectorAll('dialog').forEach(dialog => { dialog.querySelector('.close-dialog').addEventListener('click', () => dialog.close()); dialog.addEventListener('click', event => { if (event.target === dialog) { const rect = dialog.getBoundingClientRect(); if (event.clientX < rect.left || event.clientX > rect.right || event.clientY < rect.top || event.clientY > rect.bottom) dialog.close(); } }); });
document.querySelector('.privacy-trigger').addEventListener('click', () => document.querySelector('#privacy-dialog').showModal());
const form = document.querySelector('#request-form');
const status = document.querySelector('#form-status');
document.querySelectorAll('[data-service]').forEach(link => link.addEventListener('click', () => { form.elements.service.value = link.dataset.service; }));
const photo = document.querySelector('#photo');
photo.addEventListener('change', () => { const file = photo.files[0]; photo.setCustomValidity(''); if (file && (!['image/jpeg','image/png','image/webp'].includes(file.type) || file.size > 10 * 1024 * 1024)) { photo.setCustomValidity('Выберите JPG, PNG или WebP размером до 10 МБ.'); photo.reportValidity(); photo.value = ''; document.querySelector('#file-name').textContent = 'Добавить фото интерьера'; return; } document.querySelector('#file-name').textContent = file ? file.name : 'Добавить фото интерьера'; });
form.elements.phone.addEventListener('input', () => { form.elements.phone.setCustomValidity(''); status.textContent = ''; });
form.addEventListener('submit', event => { event.preventDefault(); const digits = form.elements.phone.value.replace(/\D/g, ''); if (digits.length < 10 || digits.length > 15) { form.elements.phone.setCustomValidity('Укажите телефон: от 10 до 15 цифр.'); form.elements.phone.reportValidity(); return; } status.textContent = 'Всё готово для обсуждения. Это предпросмотр: данные не отправлены и не сохранены.'; });
